"""Remove unnecessary columns

Revision ID: 73765744a1f6
Revises: 37f73a9d15d5
Create Date: 2022-04-02 11:19:02.574169+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "73765744a1f6"
down_revision = "37f73a9d15d5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("collectibles", "owned")
    op.drop_column("records", "completed")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("records", sa.Column("completed", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column("collectibles", sa.Column("owned", sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
