"""empty message

Revision ID: ef97c8cef951
Revises: f3530249ad5f
Create Date: 2022-06-01 14:51:34.843488+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ef97c8cef951"
down_revision = "f3530249ad5f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rolesCollectibles",
        sa.Column("_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("role_id", sa.BigInteger(), nullable=True),
        sa.Column("bungie_id", sa.BigInteger(), nullable=False),
        sa.Column("inverse", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.role_id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("_id"),
    )
    op.create_table(
        "rolesTriumphs",
        sa.Column("_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("role_id", sa.BigInteger(), nullable=True),
        sa.Column("bungie_id", sa.BigInteger(), nullable=False),
        sa.Column("inverse", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.role_id"], onupdate="CASCADE", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("_id"),
    )
    op.drop_table("rolesInteger")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rolesInteger",
        sa.Column(
            "_id",
            sa.INTEGER(),
            server_default=sa.text("nextval('\"rolesInteger__id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("role_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("bungie_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("inverse", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.role_id"], name="rolesInteger_role_id_fkey", onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("_id", name="rolesInteger_pkey"),
    )
    op.drop_table("rolesTriumphs")
    op.drop_table("rolesCollectibles")
    # ### end Alembic commands ###
