"""empty message

Revision ID: fe382d5e9771
Revises: 2b04ec01b78e
Create Date: 2022-08-02 08:30:27.944319+00:00

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "fe382d5e9771"
down_revision = "2b04ec01b78e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("destinyRecordDefinition")
    op.drop_table("destinyInventoryBucketDefinition")
    op.drop_table("destinySeasonPassDefinition")
    op.drop_table("destinyInventoryItemDefinition")
    op.drop_table("versions")
    op.drop_table("destinyLoreDefinition")
    op.drop_table("destinyActivityTypeDefinition")
    op.drop_table("destinyActivityModeDefinition")
    op.drop_table("destinyActivityDefinition")
    op.drop_table("destinyCollectibleDefinition")
    op.drop_table("destinyPresentationNodeDefinition")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "destinyPresentationNodeDefinition",
        sa.Column(
            "reference_id",
            sa.BIGINT(),
            server_default=sa.text("nextval('\"destinyPresentationNodeDefinition_reference_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("objective_hash", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("presentation_node_type", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "children_presentation_node_hash", postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=False
        ),
        sa.Column("children_collectible_hash", postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=False),
        sa.Column("children_record_hash", postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=False),
        sa.Column("children_metric_hash", postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=False),
        sa.Column("parent_node_hashes", postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=False),
        sa.Column("index", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column("redacted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("completion_record_hash", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("reference_id", name="destinyPresentationNodeDefinition_pkey"),
    )
    op.create_table(
        "destinyCollectibleDefinition",
        sa.Column(
            "reference_id",
            sa.BIGINT(),
            server_default=sa.text("nextval('\"destinyCollectibleDefinition_reference_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("source_hash", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("item_hash", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("parent_node_hashes", postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("reference_id", name="destinyCollectibleDefinition_pkey"),
    )
    op.create_table(
        "destinyActivityDefinition",
        sa.Column(
            "reference_id",
            sa.BIGINT(),
            server_default=sa.text("nextval('\"destinyActivityDefinition_reference_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("pgcr_image_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("activity_light_level", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("destination_hash", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("place_hash", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("activity_type_hash", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("is_pvp", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("direct_activity_mode_hash", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("direct_activity_mode_type", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column("activity_mode_hashes", postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=False),
        sa.Column("activity_mode_types", postgresql.ARRAY(sa.SMALLINT()), autoincrement=False, nullable=False),
        sa.Column("matchmade", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("max_players", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("reference_id", name="destinyActivityDefinition_pkey"),
    )
    op.create_table(
        "destinyActivityModeDefinition",
        sa.Column(
            "reference_id",
            sa.BIGINT(),
            server_default=sa.text("nextval('\"destinyActivityModeDefinition_reference_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("parent_hashes", postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=True),
        sa.Column("mode_type", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("activity_mode_category", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column("is_team_based", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("friendly_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("display", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("redacted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("reference_id", name="destinyActivityModeDefinition_pkey"),
    )
    op.create_table(
        "destinyActivityTypeDefinition",
        sa.Column(
            "reference_id",
            sa.BIGINT(),
            server_default=sa.text("nextval('\"destinyActivityTypeDefinition_reference_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("reference_id", name="destinyActivityTypeDefinition_pkey"),
    )
    op.create_table(
        "destinyLoreDefinition",
        sa.Column(
            "reference_id",
            sa.BIGINT(),
            server_default=sa.text("nextval('\"destinyLoreDefinition_reference_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("sub_title", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("redacted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("reference_id", name="destinyLoreDefinition_pkey"),
    )
    op.create_table(
        "versions",
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("version", sa.TEXT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("name", name="versions_pkey"),
    )
    op.create_table(
        "destinyInventoryItemDefinition",
        sa.Column(
            "reference_id",
            sa.BIGINT(),
            server_default=sa.text("nextval('\"destinyInventoryItemDefinition_reference_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("flavor_text", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("item_type", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column("item_sub_type", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column("class_type", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column("bucket_type_hash", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("tier_type", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column("tier_type_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("equippable", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("default_damage_type", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column("ammo_type", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("reference_id", name="destinyInventoryItemDefinition_pkey"),
    )
    op.create_table(
        "destinySeasonPassDefinition",
        sa.Column(
            "reference_id",
            sa.BIGINT(),
            server_default=sa.text("nextval('\"destinySeasonPassDefinition_reference_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("reward_progression_hash", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("prestige_progression_hash", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("index", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("reference_id", name="destinySeasonPassDefinition_pkey"),
    )
    op.create_table(
        "destinyInventoryBucketDefinition",
        sa.Column(
            "reference_id",
            sa.BIGINT(),
            server_default=sa.text("nextval('\"destinyInventoryBucketDefinition_reference_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("category", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column("item_count", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column("location", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("reference_id", name="destinyInventoryBucketDefinition_pkey"),
    )
    op.create_table(
        "destinyRecordDefinition",
        sa.Column(
            "reference_id",
            sa.BIGINT(),
            server_default=sa.text("nextval('\"destinyRecordDefinition_reference_id_seq\"'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("for_title_gilding", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("title_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("objective_hashes", postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=False),
        sa.Column("score_value", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("parent_node_hashes", postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("reference_id", name="destinyRecordDefinition_pkey"),
    )
    # ### end Alembic commands ###
