{
 "title": "ElevatorBot",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "discord_id", "label": "Discord ID", "query": "238388130581839872" },
   { "name": "server_id", "label": "Discord Server ID", "query": "669293365900214293" },
   { "name": "elevator_job", "label": "Elevator Job Name", "query": "elevator" },
   { "name": "backend_job", "label": "Backend Job Name", "query": "backend" },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "User Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "discord_id",
   "collapsed": true,
   "panels": [
    {
     "title": "Activities Played with Clan",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Activities" } },
     "targets": [
      {
       "expr": "increase(backend_clan_activity_total{job=\"$backend_job\", user_id=\"$discord_id\"}[4h])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Message Activity",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Messages" } },
     "targets": [
      {
       "expr": "sum(naff_received_messages_total{user_id=\"$discord_id\", job=\"$elevator_job\"})",
       "legendFormat": "<TOTAL>"
      },
      {
       "expr": "sum by(channel_name) (label_replace(naff_received_messages_total{user_id=\"$discord_id\", job=\"$elevator_job\"}, \"channel_name\", \"<DM>\", \"dm\", \"1\"))",
       "legendFormat": "{{channel_name}}"
      }
     ]
    },
    {
     "title": "Voice Channel Activity",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(naff_descend_voice_channel_activity_sum{job=\"$elevator_job\", user_id=\"$discord_id\"})",
       "legendFormat": "<TOTAL>"
      },
      {
       "expr": "sum by(channel_name) (naff_descend_voice_channel_activity_sum{job=\"$elevator_job\", user_id=\"$discord_id\"})",
       "legendFormat": "{{channel_name}}"
      }
     ]
    },
    {
     "title": "Voice Channel Activity",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "increase(naff_descend_voice_channel_activity_sum{job=\"$elevator_job\", user_id=\"$discord_id\"}[$__interval])",
       "legendFormat": "{{channel_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Python version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by (implementation, version) (python_info{job=\"$elevator_job\"})",
     "legendFormat": "{{implementation}} {{version}}"
    }
   ]
  },
  {
   "title": "Elevator version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elevator_version_info{job=\"$elevator_job\"}",
     "legendFormat": "Elevator {{version}}"
    }
   ]
  },
  {
   "title": "Naff version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "naff_info{job=\"$elevator_job\"}",
     "legendFormat": "Naff {{version}}"
    }
   ]
  },
  {
   "title": "Guilds per Day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 2 },
   "targets": [
    {
     "expr": "increase(naff_guilds{job=\"$elevator_job\"}[1d])"
    }
   ]
  },
  {
   "title": "Guilds Amount",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "Guilds" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "naff_guilds{job=\"$elevator_job\"}",
     "legendFormat": "Guilds"
    }
   ]
  },
  {
   "title": "Registered Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "Users" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backend_users{job=\"$backend_job\"}",
     "legendFormat": "Guilds"
    }
   ]
  },
  {
   "title": "Logged in as",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "naff_bot_info{job=\"$elevator_job\"}",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "naff_bot_start_time_info{job=\"$elevator_job\"}",
     "legendFormat": "{{datetime}}"
    }
   ]
  },
  {
   "title": "Guilds",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "guilds" } },
   "targets": [
    {
     "expr": "naff_guilds{job=\"$elevator_job\"}",
     "legendFormat": "Guilds amount"
    }
   ]
  },
  {
   "title": "Discord Websocket Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(naff_bot_latency{job=\"$elevator_job\"}[$__interval]) > 0",
     "legendFormat": "Average latency over 5 minutes"
    },
    {
     "expr": "naff_bot_latency{job=\"$elevator_job\"} > 0",
     "legendFormat": "Actual latency"
    }
   ]
  },
  {
   "title": "Global Interactions Registered",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "naff_global_interactions_registered{job=\"$elevator_job\"}",
     "legendFormat": "{instance} interactions"
    }
   ]
  },
  {
   "title": "Descend Only Interactions Registered",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "naff_descend_interactions_registered{job=\"$elevator_job\"}",
     "legendFormat": "Interactions"
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Currently Running Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Requests" } },
     "targets": [
      {
       "expr": "sum(backend_endpoints_running{job=\"$backend_job\"})",
       "legendFormat": "With token: {{with_token}}"
      }
     ]
    },
    {
     "title": "Request Execution Time",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum by(le) (increase(backend_endpoints_perf_bucket{job=\"$backend_job\"}[$__interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Total Requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "Requests" } },
     "targets": [
      {
       "expr": "sum(backend_endpoints_perf_sum{job=\"$backend_job\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "Errors" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(backend_endpoints_errors_total{job=\"$backend_job\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Bungie Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Currently Running Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "Requests" } },
     "targets": [
      {
       "expr": "sum by(with_token) (backend_bungie_running{job=\"$backend_job\"})",
       "legendFormat": "With token: {{with_token}}"
      }
     ]
    },
    {
     "title": "Request Execution Time",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sum by(le) (increase(backend_bungie_perf_bucket{job=\"$backend_job\"}[$__interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Total Requests",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "Requests" } },
     "targets": [
      {
       "expr": "sum by(with_token) (backend_bungie_perf_sum{job=\"$backend_job\"})",
       "legendFormat": "With token: {{with_token}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "Errors" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(backend_bungie_errors_total{job=\"$backend_job\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Discord Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages recieved total",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "Messages" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(naff_received_messages_total{job=\"$elevator_job\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Messages by Guild",
     "type": "piechart",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "Messages" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(guild_id, guild_name) (label_replace(naff_received_messages_total{job=\"$elevator_job\"}, \"guild_name\", \"<DM>\", \"dm\", \"1\"))",
       "legendFormat": "{{guild_name}}"
      }
     ]
    },
    {
     "title": "Messages recieved",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "Messages" } },
     "targets": [
      {
       "expr": "sum(naff_received_messages_total{job=\"$elevator_job\"})",
       "legendFormat": "<TOTAL>"
      },
      {
       "expr": "topk(10, sum by(guild_name) (label_replace(naff_received_messages_total, \"guild_name\", \"<DM>\", \"dm\", \"1\")))",
       "legendFormat": "{{guild_name}}"
      }
     ]
    },
    {
     "title": "Descend Messages",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "Messages" } },
     "targets": [
      {
       "expr": "sum(naff_received_messages_total{job=\"$elevator_job\"})",
       "legendFormat": "<TOTAL>"
      },
      {
       "expr": "sum by(channel_name) (naff_received_messages_total{job=\"$elevator_job\", guild_id=\"$server_id\"})",
       "legendFormat": "{{guild_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Discord Interactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Command Execution Time",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum(increase(naff_slash_command_perf_bucket{job=\"$elevator_job\"}[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Commands Executed",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "sum(increase(naff_slash_command_perf_count{job=\"$elevator_job\"}[$__interval]))>0",
       "legendFormat": "<TOTAL>"
      },
      {
       "expr": "label_replace(topk(10, sum(increase(naff_slash_command_perf_count{job=\"$elevator_job\"}[$__interval])>0) by (guild_name)), \"guild_name\", \"<DM>\", \"dm\", \"1\")",
       "legendFormat": "{{guild_name}}"
      }
     ]
    },
    {
     "title": "Popular Commands",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, sort_desc(label_replace(sum by(base_name, group_name, command_name) (label_replace(increase(naff_slash_command_perf_count{job=\"$elevator_job\"}[$__range]), \"group_name\", \"\", \"group_name\", \"None\")), \"command_name\", \"\", \"command_name\", \"None\"))) > 0",
       "legendFormat": "/{{base_name}} {{group_name}} {{command_name}}"
      }
     ]
    },
    {
     "title": "Command Errors",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(naff_slash_command_errors_total{job=\"$elevator_job\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Elevator",
     "type": "stat",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(name) (naff_cache_count{job=\"$elevator_job\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Backend",
     "type": "stat",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(name) (backend_cache_count{job=\"$backend_job\"})",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}